In [ ]:
import numpy as np

#Criando NumPy Arrays

In [ ]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Métodos de Construção

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye(5) ##matrix identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

##Random

In [ ]:
np.random.rand(3) #amostra aleatória entra [0, 1]

array([0.19688558, 0.9074454 , 0.05160662])

In [ ]:
np.random.rand(5, 5)

array([[0.68317624, 0.90812606, 0.37665451, 0.82258811, 0.28144747],
       [0.957026  , 0.89619619, 0.27825965, 0.54331658, 0.5975744 ],
       [0.57233019, 0.07336189, 0.54639199, 0.88398019, 0.33693058],
       [0.27626268, 0.59774263, 0.12579164, 0.32699347, 0.1239947 ],
       [0.51520243, 0.77384759, 0.72013888, 0.27434671, 0.53205382]])

In [ ]:
np.random.randn(3) #distribuição normal centrada em zero

array([-1.25614464, -0.74875985,  0.89010625])

In [ ]:
np.random.randn(5, 5)

array([[-0.55954021, -0.79077197,  0.9414695 , -0.44554589, -0.4140821 ],
       [ 1.7480824 ,  0.94631556, -0.3463165 ,  0.08872424, -1.3191439 ],
       [-0.01399794, -1.42084154,  0.88654622, -0.19215384, -0.06957348],
       [-1.02877953, -0.5521573 ,  0.61031511,  0.88759471,  0.69411785],
       [ 0.34234242,  0.20683829, -0.30664918,  0.22419605,  0.11399554]])

In [ ]:
np.random.randint(1, 100) #numero inteiro aleatória entre [1, 100] 1 pode e 100 não pode

80

In [ ]:
np.random.randint(1, 100, 200)

array([69, 37, 39, 71, 17, 47, 29, 75, 60, 59, 59, 70, 49, 18, 22,  4,  7,
       95, 17, 77,  7,  3, 46,  3, 37,  2, 82, 37, 90, 15, 46,  1, 69, 77,
       78, 39, 32, 75, 64, 62, 85, 69,  9, 53, 84, 47, 20, 38, 66, 68, 72,
       78, 10, 60, 89, 40, 24, 58, 31, 84, 54, 49, 78, 61, 16, 79, 94, 23,
       74, 95, 97, 42, 58,  6, 54, 59, 45, 22, 25, 31, 90, 41, 84, 84, 59,
       96, 86, 29, 53, 59, 63, 11, 33,  6, 10, 12, 61, 89, 76, 12, 34, 80,
       37, 96, 13, 52, 40, 71, 90, 66, 84, 17, 12, 14, 31, 98,  7, 84, 71,
       83, 29, 25, 42, 43, 18, 80, 29, 68, 42,  8, 65, 89, 51, 83, 11, 72,
        8, 77, 81, 32, 55, 29, 38, 97, 86, 62, 42,  9, 37, 35, 26, 97, 75,
       92, 73, 72, 51, 43, 44,  4, 55, 62, 57, 52, 67, 82, 44, 29, 37, 68,
       33, 76, 64, 12, 91, 83, 64, 79, 56, 84, 95, 18,  3, 17,  9, 78, 85,
       16, 30, 30, 26, 86, 74, 62, 63, 62, 24, 53, 34,  8])

##Atributos e Métodos


In [ ]:
arr = np.arange(25) #vai de 0 a 24
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0, 50, 10)
ranarr

array([ 3, 20,  2, 18, 36, 32, 49, 34, 25, 35])

In [ ]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

49

In [ ]:
ranarr.argmax() #endereço do maior numero

6

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

2

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1, 25).shape

(1, 25)

In [ ]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.dtype

dtype('int64')

##Indexação e Seleção

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[2:5] #cria um array com os elementos das posições de 2 a 5, 

array([2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5] = 100 #Brodcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
arr #array original foi mudado

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#Indexando um array 2D (Matrizes)

In [ ]:
#obs: o formato geral é arr_2d[row][col] ou arr_2d[row, col]
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1] #imprime a linha

array([20, 25, 30])

In [ ]:
arr_2d[1, 0] #elemento na linha

20

In [ ]:
arr_2d[:2, 1:] #pega da linha 0 até a linah 2, mas a 2 ele não usa, e os elemente a partir da posição 1

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:, 2] #usar a linha inteira, mas pega só a coluna

array([15, 30, 45])

In [ ]:
#Indexação Sofisticada (Fancy Indexing)
arr2d = np.zeros((10, 10))

arr_length = arr2d.shape[1]

for i in range(arr_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2, 4, 6, 8]] #isso só visualiza a matrix, nao altera ela

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[6, 4, 2, 7]] #isso só visualiza a matrix, nao altera ela

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

##Seleção

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr] #verifica os elementos True e imprime

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr > x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

#Operações no NumPy

##Aritmética

In [ ]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

<ipython-input-106-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

<ipython-input-107-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
arr #o array não foi alterado

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Funções Universais

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr)

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-114-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])